from __future__ import annotations

import os

for k, v in {
    'HARIZON_PUBLICATION_TIER_MODE': 'hybrid',
    'HARIZON_A_TIER_ONLY': 'false',
    'PUBLISH_ALLOW_B_TIER': 'true',
    'CONTROLLED_FALLBACK_ALLOW_B_TIER': 'true',
    'CONTROLLED_FALLBACK_TELEGRAM_ALLOW_TIER_B': 'true',
    'CONTROLLED_FALLBACK_TIER_B_ENABLED': 'true',
    'CONTROLLED_FALLBACK_TIER_A_REQUIRE_2_ODDS_SOURCES': 'false',
    'CONTROLLED_FALLBACK_TIER_A_MIN_BOOKS': '2',
    'CONTROLLED_FALLBACK_TIER_A_MIN_CONTEXT_SOURCES': '2',
    'CONTROLLED_FALLBACK_TIER_A_MIN_CONFIRMATION_SOURCES': '2',
    'CONTROLLED_FALLBACK_TIER_B_MIN_BOOKS': '2',
    'CONTROLLED_FALLBACK_TIER_B_MIN_CONTEXT_SOURCES': '1',
    'CONTROLLED_FALLBACK_TIER_B_MIN_CONFIRMATION_SOURCES': '1',
    'CONTROLLED_FALLBACK_REQUIRE_INDEPENDENT_SOURCES': 'false',
    'SPORTLOGIC_ENABLED': 'false',
    'ENABLE_SPORTLOGIC': 'false',
    'DAY_INVENTORY_ENABLE_SPORTLOGIC': 'false',
}.items():
    os.environ[k] = v
