from __future__ import annotations

import os

for k, v in {
    'HARIZON_PUBLICATION_TIER_MODE': 'hybrid',
    'HARIZON_A_TIER_ONLY': 'false',
    'PUBLISH_ALLOW_B_TIER': 'true',
    'CONTROLLED_FALLBACK_ALLOW_B_TIER': 'true',
    'CONTROLLED_FALLBACK_TELEGRAM_ALLOW_TIER_B': 'true',
    'CONTROLLED_FALLBACK_TIER_B_ENABLED': 'true',
    'CONTROLLED_FALLBACK_TIER_A_REQUIRE_2_ODDS_SOURCES': 'false',
    'CONTROLLED_FALLBACK_TIER_A_MIN_BOOKS': '2',
    'CONTROLLED_FALLBACK_TIER_A_MIN_CONTEXT_SOURCES': '2',
    'CONTROLLED_FALLBACK_TIER_A_MIN_CONFIRMATION_SOURCES': '2',
    'CONTROLLED_FALLBACK_TIER_B_MIN_BOOKS': '2',
    'CONTROLLED_FALLBACK_TIER_B_MIN_CONTEXT_SOURCES': '2',
    'CONTROLLED_FALLBACK_TIER_B_MIN_CONFIRMATION_SOURCES': '2',
    'CONTROLLED_FALLBACK_REQUIRE_INDEPENDENT_SOURCES': 'false',
    'BZZOIRO_SCOPE_TARGET_LIMIT': '300',
    'BZZOIRO_V2_SOURCE_MATRIX_TARGET_LIMIT': '300',
    'BZZOIRO_CONTEXT_GAP_MATCH_LIMIT': '300',
    'BZZOIRO_V2_MATCH_LIMIT': '220',
    'BZZOIRO_CONTEXT_MATCH_LIMIT': '300',
    'SSTATS_CONTEXT_MATCH_LIMIT': '300',
    'SSTATS_DEEP_CONTEXT_MATCH_LIMIT': '200',
    'CONTEXT_ENRICHMENT_MATCH_LIMIT': '300',
    'DAY_INVENTORY_CONTEXT_BACKFILL_LIMIT': '300',
    'SPORTLOGIC_ENABLED': 'false',
    'ENABLE_SPORTLOGIC': 'false',
    'DAY_INVENTORY_ENABLE_SPORTLOGIC': 'false',
}.items():
    os.environ[k] = v
